### ISSUE TITLE
Typing delay when recording new interactions

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#2]

**Comment by tmfrnz** [comment]
improved performance by wrapping "new entity" forms and avoiding re-calculation of form fields. 

if improvement is still not satisfactory, we can further try deferring/debouncing the form input

**Comment by hohuuhuy** [comment]
After further testing, I think that the delay is lessened but still quite present. Maybe we should try the other solution you mentioned and see how it goes?

**Comment by tmfrnz** [comment]
will do!

**Comment by hohuuhuy** [comment]
More information re typing delay @tmfrnz 

- Browsers: seems like the issue is the same on both Chrome and Safari, and particularly bad on Chrome on mobile
- Forms:
   - the forms when creating new, or editing existing one have some delay — the words still appear as you type, albeit with a 1-2 sec delay
   - the forms that appear on top of/ overlaying the main screen (when you create a new entity while already creating or editing another one in the background, e.g. creating new contact while creating a new interaction) have the worst delay — the words don't appear until 1-2 sec after you finish typing a whole sentence

**Comment by tmfrnz** [comment]
thanks @hohuuhuy - will look into this shortly!

**Comment by tmfrnz** [comment]
adding 0.5s debounce
https://github.com/dumparkltd/advocacy-tracker-client/commit/5f310cb7b29a9d60babcec4fea04e6c8127c9d01

**Comment by tmfrnz** [comment]
@hohuuhuy here a bit of background on the improvements:

the issue was that the form validated any user input right after every keystroke, resulting in a full form re-render and a re-calculation of all form content including multi-select options

so in the first step I isolated the form from the page views so that the form content is only calculated once and not with every form change

in addition I just now added a 0.5s delay to all input fields, so that the field validation and and form re-rendering does no longer happen on every keystroke but only 0.5s after the last key stroke (so only when input is paused)

we can by the way easily change that delay (shorten it a bit if you are all rather fast writers or increase it if you are all rather slow)
